__author__ = 'mazzalex02'

NAME = "Cane"
KIND = "cane"

DESCRIPTION = "An old cane for young magicians."

DURABILITY = 100

PIERCE_DAMAGE_MODIFIER = 0.00

SLASH_DAMAGE_MODIFIER = 0.00

IMPACT_DAMAGE_MODIFIER = 0.70

RANGED_DAMAGE_MODIFIER = 0.00

MAGIC_DAMAGE_MODIFIER = 1.10
